version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tuan2-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tuan2_db
      MYSQL_USER: tuan2_user
      MYSQL_PASSWORD: tuan2_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: tuan2-spring-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: tuan2_db
      DB_USERNAME: tuan2_user
      DB_PASSWORD: tuan2_password
      APPLICATION_SECURITY_JWT_SECRET_KEY: your-secure-random-key-here
      APPLICATION_SECURITY_JWT_EXPIRATION: 86400000
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]

volumes:
  db_data: